export const HEADER_SIZE = 512

export const FILENAME_OFFSET = 0
export const FILENAME_FIELD_LENGTH = 100
export const FILENAME_PREFIX_OFFSET = 345
export const FILENAME_PREFIX_FIELD_LENGTH = 155

export const FILEMODE_OFFSET = 100
export const FILEMODE_FIELD_LENGTH = 8

export const FILESIZE_OFFSET = 124
export const FILESIZE_FIELD_LENGTH = 12

export const LINK_INDICATOR_OFFSET = 156
export const LINK_INDICATOR_FIELD_LENGTH = 1

export const LINKED_FILENAME_OFFSET = 157
export const LINKED_FILENAME_FIELD_LENGTH = 100

export const USTART_INDICATOR_OFFSET = 257
export const USTAR_INDICATOR_FIELD_LENGTH = 6

export const USTAR_INDICATOR = "ustar"
